name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
#        python-version: ["3.8", "3.9", "3.10", "3.11"]
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Ubuntu Dependencies
        run: |
          sudo apt-get update
          sudo apt install -y xauth tesseract-ocr  # for pin-the-tail

      - name: Install dependencies
        run: |
          python -m pip install poetry
          poetry install

      - name: Test with pytest
        run: |
          poetry run python -m pytest --durations=5 --durations-min=0.04 --cov=donkey_see_donkey_do/ --cov-report term-missing:skip-covered

      - name: Run pre-commit checks
        run: |
          poetry run pre-commit run --all-files
          if [[ `git status --porcelain` ]]; then
              echo 'One or more files needs to be formatted, please run pre-commit run --all-files'
              exit 1
          fi
